dist: xenial
language: cpp

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7

script:
  - make
  - bin/ElephantTest