language: cpp

os: freebsd
addons:
  pkg:
    - llvm90
  env:
    - CC=/usr/local/bin/clang90    # llvm90 installs it to /usr/local/bin/clang90
    - CXX=/usr/local/bin/clang++90 # llvm90 installs it to /usr/local/bin/clang++90

before_script:
  - cmake .

script:
  - make
  - bin/ElephantTest