#include "bench_command.hpp"
#include "fen_command.hpp"
#include "new_game_command.hpp"
#include "simple_commands.hpp"
#include "help_command.hpp"
#include "print_command.hpp"
#include "divide_command.hpp"
#include "move_command.hpp"